/** WooCommerce province codes for Thailand (country TH). */
export const THAI_PROVINCES = [
  { code: "TH-10", en: "Bangkok", th: "กรุงเทพมหานคร" },
  { code: "TH-11", en: "Samut Prakan", th: "สมุทรปราการ" },
  { code: "TH-12", en: "Nonthaburi", th: "นนทบุรี" },
  { code: "TH-13", en: "Pathum Thani", th: "ปทุมธานี" },
  { code: "TH-14", en: "Phra Nakhon Si Ayutthaya", th: "พระนครศรีอยุธยา" },
  { code: "TH-15", en: "Ang Thong", th: "อ่างทอง" },
  { code: "TH-16", en: "Lopburi", th: "ลพบุรี" },
  { code: "TH-17", en: "Sing Buri", th: "สิงห์บุรี" },
  { code: "TH-18", en: "Chai Nat", th: "ชัยนาท" },
  { code: "TH-19", en: "Saraburi", th: "สระบุรี" },
  { code: "TH-20", en: "Chonburi", th: "ชลบุรี" },
  { code: "TH-21", en: "Rayong", th: "ระยอง" },
  { code: "TH-22", en: "Chanthaburi", th: "จันทบุรี" },
  { code: "TH-23", en: "Trat", th: "ตราด" },
  { code: "TH-24", en: "Chachoengsao", th: "ฉะเชิงเทรา" },
  { code: "TH-25", en: "Prachin Buri", th: "ปราจีนบุรี" },
  { code: "TH-26", en: "Nakhon Nayok", th: "นครนายก" },
  { code: "TH-27", en: "Sa Kaeo", th: "สระแก้ว" },
  { code: "TH-30", en: "Nakhon Ratchasima", th: "นครราชสีมา" },
  { code: "TH-31", en: "Buri Ram", th: "บุรีรัมย์" },
  { code: "TH-32", en: "Surin", th: "สุรินทร์" },
  { code: "TH-33", en: "Sisaket", th: "ศรีสะเกษ" },
  { code: "TH-34", en: "Ubon Ratchathani", th: "อุบลราชธานี" },
  { code: "TH-35", en: "Yasothon", th: "ยโสธร" },
  { code: "TH-36", en: "Chaiyaphum", th: "ชัยภูมิ" },
  { code: "TH-37", en: "Amnat Charoen", th: "อำนาจเจริญ" },
  { code: "TH-38", en: "Bueng Kan", th: "บึงกาฬ" },
  { code: "TH-39", en: "Nong Bua Lam Phu", th: "หนองบัวลำภู" },
  { code: "TH-40", en: "Khon Kaen", th: "ขอนแก่น" },
  { code: "TH-41", en: "Udon Thani", th: "อุดรธานี" },
  { code: "TH-42", en: "Loei", th: "เลย" },
  { code: "TH-43", en: "Nong Khai", th: "หนองคาย" },
  { code: "TH-44", en: "Maha Sarakham", th: "มหาสารคาม" },
  { code: "TH-45", en: "Roi Et", th: "ร้อยเอ็ด" },
  { code: "TH-46", en: "Kalasin", th: "กาฬสินธุ์" },
  { code: "TH-47", en: "Sakon Nakhon", th: "สกลนคร" },
  { code: "TH-48", en: "Nakhon Phanom", th: "นครพนม" },
  { code: "TH-49", en: "Mukdahan", th: "มุกดาหาร" },
  { code: "TH-50", en: "Chiang Mai", th: "เชียงใหม่" },
  { code: "TH-51", en: "Lamphun", th: "ลำพูน" },
  { code: "TH-52", en: "Lampang", th: "ลำปาง" },
  { code: "TH-53", en: "Uttaradit", th: "อุตรดิตถ์" },
  { code: "TH-54", en: "Phrae", th: "แพร่" },
  { code: "TH-55", en: "Nan", th: "น่าน" },
  { code: "TH-56", en: "Phayao", th: "พะเยา" },
  { code: "TH-57", en: "Chiang Rai", th: "เชียงราย" },
  { code: "TH-58", en: "Mae Hong Son", th: "แม่ฮ่องสอน" },
  { code: "TH-60", en: "Nakhon Sawan", th: "นครสวรรค์" },
  { code: "TH-61", en: "Uthai Thani", th: "อุทัยธานี" },
  { code: "TH-62", en: "Kamphaeng Phet", th: "กำแพงเพชร" },
  { code: "TH-63", en: "Tak", th: "ตาก" },
  { code: "TH-64", en: "Sukhothai", th: "สุโขทัย" },
  { code: "TH-65", en: "Phitsanulok", th: "พิษณุโลก" },
  { code: "TH-66", en: "Phichit", th: "พิจิตร" },
  { code: "TH-67", en: "Phetchabun", th: "เพชรบูรณ์" },
  { code: "TH-70", en: "Ratchaburi", th: "ราชบุรี" },
  { code: "TH-71", en: "Kanchanaburi", th: "กาญจนบุรี" },
  { code: "TH-72", en: "Suphan Buri", th: "สุพรรณบุรี" },
  { code: "TH-73", en: "Nakhon Pathom", th: "นครปฐม" },
  { code: "TH-74", en: "Samut Sakhon", th: "สมุทรสาคร" },
  { code: "TH-75", en: "Samut Songkhram", th: "สมุทรสงคราม" },
  { code: "TH-76", en: "Phetchaburi", th: "เพชรบุรี" },
  { code: "TH-77", en: "Prachuap Khiri Khan", th: "ประจวบคีรีขันธ์" },
  { code: "TH-80", en: "Nakhon Si Thammarat", th: "นครศรีธรรมราช" },
  { code: "TH-81", en: "Krabi", th: "กระบี่" },
  { code: "TH-82", en: "Phang Nga", th: "พังงา" },
  { code: "TH-83", en: "Phuket", th: "ภูเก็ต" },
  { code: "TH-84", en: "Surat Thani", th: "สุราษฎร์ธานี" },
  { code: "TH-85", en: "Ranong", th: "ระนอง" },
  { code: "TH-86", en: "Chumphon", th: "ชุมพร" },
  { code: "TH-90", en: "Songkhla", th: "สงขลา" },
  { code: "TH-91", en: "Satun", th: "สตูล" },
  { code: "TH-92", en: "Trang", th: "ตรัง" },
  { code: "TH-93", en: "Phatthalung", th: "พัทลุง" },
  { code: "TH-94", en: "Pattani", th: "ปัตตานี" },
  { code: "TH-95", en: "Yala", th: "ยะลา" },
  { code: "TH-96", en: "Narathiwat", th: "นราธิวาส" },
] as const;

export function provinceLabel(
  code: string,
  lang: "en" | "th",
): string {
  const p = THAI_PROVINCES.find((x) => x.code === code);
  if (!p) return code;
  return lang === "th" ? p.th : p.en;
}
